CREATE TABLE Universiteler
(
	Id INT PRIMARY KEY IDENTITY,
	Ad NVARCHAR(100) NOT NULL
);

INSERT INTO Universiteler(Ad) VALUES
(N'Adana Bilim ve Teknoloji Üniversitesi'),
(N'Çukurova Üniversitesi'),
(N'Adıyaman Üniversitesi'),
(N'Afyon Kocatepe Üniversitesi'),
(N'Afyonkarahisar Sağlık Bilimleri Üniversitesi'),
(N'Ağrı İbrahim Çeçen Üniversitesi'),
(N'Aksaray Üniversitesi'),
(N'Amasya Üniversitesi'),
(N'Ankara Üniversitesi'),
(N'Ankara Müzik ve Güzel Sanatlar Üniversitesi'),
(N'Ankara Hacı Bayram Veli Üniversitesi'),
(N'Ankara Sosyal Bilimler Üniversitesi'),
(N'Gazi Üniversitesi'),
(N'Hacettepe Üniversitesi'),
(N'Orta Doğu Teknik Üniversitesi'),
(N'Ankara Yıldırım Beyazıt Üniversitesi'),
(N'Polis Akademisi'),
(N'Anka Teknoloji Üniversitesi'),
(N'Ankara Bilim Üniversitesi'),
(N'Ankara Medipol Üniversitesi'),
(N'Atılım Üniversitesi'),
(N'Başkent Üniversitesi'),
(N'Çankaya Üniversitesi'),
(N'İhsan Doğramacı Bilkent Üniversitesi'),
(N'Lokman Hekim Üniversitesi'),
(N'Ostim Teknik Üniversitesi'),
(N'TED Üniversitesi'),
(N'TOBB Ekonomi ve Teknoloji Üniversitesi'),
(N'Ufuk Üniversitesi'),
(N'Türk Hava Kurumu Üniversitesi'),
(N'Yüksek İhtisas Üniversitesi'),
(N'Akdeniz Üniversitesi'),
(N'Alanya Alaaddin Keykubat Üniversitesi'),
(N'Alanya Hamdullah Emin Paşa Üniversitesi'),
(N'Antalya Akev Üniversitesi'),
(N'Antalya Bilim Üniversitesi'),
(N'Ardahan Üniversitesi'),
(N'Artvin Çoruh Üniversitesi'),
(N'Aydın Adnan Menderes Üniversitesi'),
(N'Balıkesir Üniversitesi'),
(N'Bandırma Onyedi Eylül Üniversitesi'),
(N'Bartın Üniversitesi'),
(N'Batman Üniversitesi'),
(N'Bayburt Üniversitesi'),
(N'Bilecik Şeyh Edebali Üniversitesi'),
(N'Bingöl Üniversitesi'),
(N'Bitlis Eren Üniversitesi'),
(N'Bolu Abant İzzet Baysal Üniversitesi'),
(N'Burdur Mehmet Akif Ersoy Üniversitesi'),
(N'Bursa Teknik Üniversitesi'),
(N'Bursa Uludağ Üniversitesi'),
(N'Çanakkale Onsekiz Mart Üniversitesi'),
(N'Çankırı Karatekin Üniversitesi'),
(N'Hitit Üniversitesi'),
(N'Pamukkale Üniversitesi'),
(N'Dicle Üniversitesi'),
(N'Düzce Üniversitesi'),
(N'Trakya Üniversitesi'),
(N'Fırat Üniversitesi'),
(N'Erzincan Binali Yıldırım Üniversitesi'),
(N'Atatürk Üniversitesi'),
(N'Erzurum Teknik Üniversitesi'),
(N'Anadolu Üniversitesi'),
(N'Eskişehir Osmangazi Üniversitesi'),
(N'Eskişehir Teknik Üniversitesi'),
(N'Gaziantep Üniversitesi'),
(N'Gaziantep İslam Bilim ve Teknoloji Üniversitesi'),
(N'Hasan Kalyoncu Üniversitesi'),
(N'Sanko Üniversitesi'),
(N'Giresun Üniversitesi'),
(N'Gümüşhane Üniversitesi'),
(N'Hakkari Üniversitesi'),
(N'İskenderun Teknik Üniversitesi'),
(N'Hatay Mustafa Kemal Üniversitesi'),
(N'Iğdır Üniversitesi'),
(N'Süleyman Demirel Üniversitesi'),
(N'Isparta Uygulamalı Bilimler Üniversitesi'),
(N'Boğaziçi Üniversitesi'),
(N'Galatasaray Üniversitesi'),
(N'İstanbul Medeniyet Üniversitesi'),
(N'İstanbul Teknik Üniversitesi'),
(N'İstanbul Üniversitesi'),
(N'İstanbul Üniversitesi-Cerrahpaşa'),
(N'Marmara Üniversitesi'),
(N'Milli Savunma Üniversitesi (Askerî)'),
(N'Mimar Sinan Güzel Sanatlar Üniversitesi'),
(N'Türkiye Uluslararası İslam, Bilim ve Teknoloji Üniversitesi'),
(N'Türk-Alman Üniversitesi'),
(N'Türk-Japon Bilim ve Teknoloji Üniversitesi'),
(N'Sağlık Bilimleri Üniversitesi'),
(N'Yıldız Teknik Üniversitesi'),
(N'Acıbadem Üniversitesi'),
(N'Bahçeşehir Üniversitesi'),
(N'Beykent Üniversitesi'),
(N'Bezmialem Vakıf Üniversitesi'),
(N'Biruni Üniversitesi'),
(N'Doğuş Üniversitesi'),
(N'Fatih Sultan Mehmet Üniversitesi'),
(N'Fenerbahçe Üniversitesi'),
(N'Gedik Üniversitesi'),
(N'Haliç Üniversitesi'),
(N'Işık Üniversitesi'),
(N'İbn Haldun Üniversitesi'),
(N'İstanbul 29 Mayıs Üniversitesi'),
(N'Altınbaş Üniversitesi'),
(N'İstanbul Arel Üniversitesi'),
(N'İstanbul Atlas Üniversitesi'),
(N'İstanbul Aydın Üniversitesi'),
(N'İstanbul Ayvansaray Üniversitesi'),
(N'Beykoz Üniversitesi'),
(N'İstanbul Bilgi Üniversitesi'),
(N'İstanbul Galata Üniversitesi'),
(N'Demiroğlu Bilim Üniversitesi'),
(N'İstanbul Ticaret Üniversitesi'),
(N'İstanbul Esenyurt Üniversitesi'),
(N'İstanbul Gedik Üniversitesi'),
(N'İstanbul Gelişim Üniversitesi'),
(N'İstanbul Kent Üniversitesi'),
(N'İstanbul Kültür Üniversitesi'),
(N'İstanbul Medipol Üniversitesi'),
(N'İstanbul Okan Üniversitesi'),
(N'İstanbul Rumeli Üniversitesi'),
(N'İstanbul Sabahattin Zaim Üniversitesi'),
(N'İstinye Üniversitesi'),
(N'Kadir Has Üniversitesi'),
(N'Koç Üniversitesi'),
(N'Maltepe Üniversitesi'),
(N'MEF Üniversitesi'),
(N'Nişantaşı Üniversitesi'),
(N'Özyeğin Üniversitesi'),
(N'Piri Reis Üniversitesi'),
(N'Sabancı Üniversitesi'),
(N'İstanbul Sağlık ve Teknoloji Üniversitesi'),
(N'Üsküdar Üniversitesi'),
(N'Yeditepe Üniversitesi'),
(N'Yeni Yüzyıl Üniversitesi'),
(N'Dokuz Eylül Üniversitesi'),
(N'Ege Üniversitesi'),
(N'İzmir Yüksek Teknoloji Enstitüsü'),
(N'İzmir Kâtip Çelebi Üniversitesi'),
(N'İzmir Bakırçay Üniversitesi'),
(N'İzmir Demokrasi Üniversitesi'),
(N'İzmir Ekonomi Üniversitesi'),
(N'İzmir Tınaztepe Üniversitesi'),
(N'Yaşar Üniversitesi'),
(N'Kahramanmaraş Sütçü İmam Üniversitesi'),
(N'Kahramanmaraş İstiklal Üniversitesi'),
(N'Karabük Üniversitesi'),
(N'Karamanoğlu Mehmetbey Üniversitesi'),
(N'Kafkas Üniversitesi'),
(N'Kastamonu Üniversitesi'),
(N'Abdullah Gül Üniversitesi'),
(N'Erciyes Üniversitesi'),
(N'Kayseri Üniversitesi'),
(N'Nuh Naci Yazgan Üniversitesi'),
(N'Kırıkkale Üniversitesi'),
(N'Kırklareli Üniversitesi'),
(N'Kırşehir Ahi Evran Üniversitesi'),
(N'Kilis 7 Aralık Üniversitesi'),
(N'Gebze Teknik Üniversitesi'),
(N'Kocaeli Üniversitesi'),
(N'Kocaeli Sağlık ve Teknoloji Üniversitesi'),
(N'Konya Teknik Üniversitesi'),
(N'Necmettin Erbakan Üniversitesi'),
(N'Selçuk Üniversitesi'),
(N'Konya Gıda ve Tarım Üniversitesi'),
(N'KTO Karatay Üniversitesi'),
(N'Kütahya Dumlupınar Üniversitesi'),
(N'Kütahya Sağlık Bilimleri Üniversitesi'),
(N'İnönü Üniversitesi'),
(N'Malatya Turgut Özal Üniversitesi'),
(N'Manisa Celal Bayar Üniversitesi'),
(N'Mardin Artuklu Üniversitesi'),
(N'Mersin Üniversitesi'),
(N'Tarsus Üniversitesi'),
(N'Çağ Üniversitesi'),
(N'Toros Üniversitesi'),
(N'Muğla Sıtkı Koçman Üniversitesi'),
(N'Muş Alparslan Üniversitesi'),
(N'Nevşehir Hacı Bektaş Veli Üniversitesi'),
(N'Kapadokya Üniversitesi'),
(N'Niğde Ömer Halisdemir Üniversitesi'),
(N'Ordu Üniversitesi'),
(N'Osmaniye Korkut Ata Üniversitesi'),
(N'Recep Tayyip Erdoğan Üniversitesi'),
(N'Sakarya Üniversitesi'),
(N'Sakarya Uygulamalı Bilimler Üniversitesi'),
(N'Ondokuz Mayıs Üniversitesi'),
(N'Samsun Üniversitesi'),
(N'Siirt Üniversitesi'),
(N'Sinop Üniversitesi'),
(N'Sivas Cumhuriyet Üniversitesi'),
(N'Sivas Bilim ve Teknoloji Üniversitesi'),
(N'Harran Üniversitesi'),
(N'Şırnak Üniversitesi'),
(N'Tekirdağ Namık Kemal Üniversitesi'),
(N'Tokat Gaziosmanpaşa Üniversitesi'),
(N'Karadeniz Teknik Üniversitesi'),
(N'Trabzon Üniversitesi'),
(N'Avrasya Üniversitesi'),
(N'Munzur Üniversitesi'),
(N'Uşak Üniversitesi'),
(N'Van Yüzüncü Yıl Üniversitesi'),
(N'Yalova Üniversitesi'),
(N'Yozgat Bozok Üniversitesi'),
(N'Zonguldak Bülent Ecevit Üniversitesi');
